import { Product } from "@/types";

export const products: Product[] = [
  {
    id: 1,
    name: "TLS Knit Cap",
    category: "knit-cap",
    shortDescription: "Some description goes here",
    price: 32,
    oldPrice: 56,
    image: "/images/bonnet.webp",
    link: "/product",
  },
  {
    id: 2,
    name: "TLS Dress",
    category: "knit-cap",
    shortDescription: "Some description goes here",
    price: 69,
    oldPrice: 119,
    image: "/images/dress.webp",
    link: "/product",
  },
  {
    id: 3,
    name: "Clein Sports Bottle",
    category: "flask",
    shortDescription: "Some description goes here",
    price: 22,
    image: "/images/gourde1.webp",
    link: "/product",
  },
  {
    id: 4,
    name: "Nike Sports Bottle",
    category: "flask",
    shortDescription: "Some description goes here",
    price: 29,
    image: "/images/gourde2.webp",
    link: "/product",
  },
  {
    id: 5,
    name: "LA T-Shirt",
    category: "t-shirt",
    shortDescription: "Some description goes here",
    price: 19,
    image: "/images/t-shirt1.webp",
    link: "/product",
  },
  {
    id: 6,
    name: "Nike custom T-Shirt",
    category: "t-shirt",
    shortDescription: "Some description goes here",
    price: 26,
    oldPrice: 39,
    image: "/images/t-shirt2.webp",
    link: "/product",
  },
  {
    id: 7,
    name: "CAL Long Sleeve",
    category: "longslive t-shirt",
    shortDescription: "Tailus UI California mood t-shirt",
    price: 26,
    oldPrice: 39,
    image: "/images/t-shirt-l1.webp",
    link: "/product",
  },
  {
    id: 8,
    name: "705 Long Sleeve",
    category: "longslive t-shirt",
    shortDescription: "Tailus UI Lubumbashi mood t-shirt",
    price: 26,
    oldPrice: 39,
    image: "/images/t-shirt-l2.webp",
    link: "/product",
  },
  {
    id: 9,
    name: "CAL Long Sleeve",
    category: "longslive t-shirt",
    shortDescription: "Tailus UI California mood t-shirt",
    price: 26,
    oldPrice: 39,
    image: "/images/t-shirt-l3.webp",
    link: "/product",
  },
];
